name: Windows - Playit Agent

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Download Downloads.bat
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/dc5k31ly8b4a3uayf5riu/Downloads.bat?rlkey=j9wpfkcrq7d9o49rzwizxrjg6&st=wgu2vdps&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Download and Install Playit Agent
        run: |
          curl -s -L -o C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe https://github.com/playit-cloud/playit-agent/releases/download/v0.15.13/playit-windows-x86-signed.exe
          Start-Process -FilePath "C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe"

      - name: Wait for Console to Appear
        run: |
          Start-Sleep -Seconds 10  # Подождать 10 секунд, чтобы консольное окно успело отобразиться

      - name: Capture Console Output
        run: |
          type nul > C:\Users\runneradmin\Downloads\console_output.txt  # Создать пустой файл для записи вывода
          Start-Process -FilePath "C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe" -RedirectStandardOutput "C:\Users\runneradmin\Downloads\console_output.txt"

      - name: Display Console Output
        run: type C:\Users\runneradmin\Downloads\console_output.txt  # Вывести содержимое файла console_output.txt
