name: Windows - Playit Agent

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Download Downloads.bat
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/p8z289sj5799jvmrbozk5/Downloads.bat?rlkey=zzz5u4dsgf3oj04v6to766h53&st=0r96rqoh&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Download and Install Playit Agent
        run: |
          curl -L -o playit-agent.exe https://github.com/playit-cloud/playit-agent/releases/download/v0.15.13/playit-windows-x86-signed.exe
          start "" "playit-agent.exe"

      - name: Wait for Console to Appear
        run: |
          timeout /t 10  # Подождать 10 секунд, чтобы консольное окно успело отобразиться

      - name: Capture Console Output
        run: |
          type nul > console_output.txt  # Создать пустой файл для записи вывода
          start cmd /c "playit-agent.exe > console_output.txt"

      - name: Display Console Output
        run: type console_output.txt  # Вывести содержимое файла console_output.txt