name: Windows - Playit Agent

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Download Downloads.bat
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/dc5k31ly8b4a3uayf5riu/Downloads.bat?rlkey=j9wpfkcrq7d9o49rzwizxrjg6&st=u5z7zq5l&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Download and Install Playit Agent
        run: |
          curl -s -L -o C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe https://github.com/playit-cloud/playit-agent/releases/download/v0.15.13/playit-windows-x86-signed.exe
          Start-Process -FilePath "C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe"

      - name: Wait for Console to Appear
        run: |
          Start-Sleep -Seconds 10  # Подождать 10 секунд, чтобы консольное окно успело отобразиться

      - name: Create Empty File for Console Output
        run: |
          New-Item -Path C:\Users\runneradmin\Downloads\console_output.txt -ItemType File -Force

      - name: Capture Console Output
        run: |
          Start-Process -FilePath "C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe" -RedirectStandardOutput "C:\Users\runneradmin\Downloads\console_output.txt" -NoNewWindow -Wait

      - name: Display Console Output
        run: Get-Content C:\Users\runneradmin\Downloads\console_output.txt  # Вывести содержимое файла console_output.txt
