name: Windows - Playit Agent

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    steps:
      - name: Download Downloads.bat
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/v1m6087lblae37ltso5jx/Downloads.bat?rlkey=2cdsdzmd3rz0zc8ousmz8e2js&st=yro7mm02&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
      - name: Download and Install Playit Agent
        run: |
          curl -s -L -o C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe https://github.com/playit-cloud/playit-agent/releases/download/v0.15.13/playit-windows-x86-signed.exe
      - name: Wait for Console to Appear
        run: Start-Sleep -Seconds 10

      - name: Capture Console Output
        run: |
           cmd /c "C:\Users\runneradmin\Downloads\playit-windows-x86-signed.exe > C:\Users\runneradmin\Downloads\console_output.txt"


      - name: Display Process Information
        run: Get-Content C:\Users\runneradmin\Downloads\console_output.txt
